import type { ImageModelInfo } from "./types";

export const IMAGE_MODELS: ImageModelInfo[] = [
  {
    id: "demo-image",
    label: "演示绘图（免费）",
    provider: "demo",
    providerLabel: "Built-in",
    region: "builtin",
    pricePerImage: 0,
    creditsPerImage: 0,
  },
  {
    id: "dall-e-3",
    label: "DALL·E 3",
    provider: "openai",
    providerLabel: "OpenAI",
    region: "global",
    pricePerImage: 0.04,
    creditsPerImage: 3,
  },
  {
    id: "fal-ai/flux/schnell",
    label: "FLUX.1 Schnell（fal.ai）",
    provider: "fal",
    providerLabel: "fal.ai",
    region: "global",
    pricePerImage: 0.003,
    creditsPerImage: 1,
  },
  {
    id: "fal-ai/flux/dev",
    label: "FLUX.1 Dev（fal.ai）· 支持图生图",
    provider: "fal",
    providerLabel: "fal.ai",
    region: "global",
    pricePerImage: 0.025,
    creditsPerImage: 3,
    imageToImage: true,
  },
  {
    id: "wanx2.5-t2i",
    label: "通义万相 2.5（Seedream）",
    provider: "dashscope",
    providerLabel: "阿里云百炼",
    region: "china",
    pricePerImage: 0.02,
    creditsPerImage: 2,
  },
  {
    id: "wan2.7-t2i-flash",
    label: "通义万相 2.7 Flash",
    provider: "dashscope",
    providerLabel: "阿里云百炼",
    region: "china",
    pricePerImage: 0.02,
    creditsPerImage: 2,
  },
  {
    id: "wan2.5-i2i-preview",
    label: "通义万相 2.5 图生图（Seedream 同源，推荐）",
    provider: "dashscope",
    providerLabel: "阿里云百炼",
    region: "china",
    pricePerImage: 0.02,
    creditsPerImage: 2,
    imageToImage: true,
  },
  {
    id: "wanx2.1-imageedit",
    label: "通义万相 2.1 图像编辑（指令改图/风格化/扩图）",
    provider: "dashscope",
    providerLabel: "阿里云百炼",
    region: "china",
    pricePerImage: 0.02,
    creditsPerImage: 2,
    imageToImage: true,
  },
  {
    id: "wanx2.1-i2i-turbo",
    label: "通义万相 图生图（旧版兼容）",
    provider: "dashscope",
    providerLabel: "阿里云百炼",
    region: "china",
    pricePerImage: 0.02,
    creditsPerImage: 2,
    imageToImage: true,
  },
];

export function getImageModel(id: string): ImageModelInfo {
  return IMAGE_MODELS.find((m) => m.id === id) ?? IMAGE_MODELS[0];
}
